INSERT INTO GENRES VALUES ( 1, 'Комедия' );
INSERT INTO GENRES VALUES ( 2, 'Драма' );
INSERT INTO GENRES VALUES ( 3, 'Мультфильм' );
INSERT INTO GENRES VALUES ( 4, 'Триллер' );
INSERT INTO GENRES VALUES ( 5, 'Документальный' );
INSERT INTO GENRES VALUES ( 6, 'Боевик' );

INSERT INTO MPA_RATINGS VALUES ( 1, 'G' );
INSERT INTO MPA_RATINGS VALUES ( 2, 'PG' );
INSERT INTO MPA_RATINGS VALUES ( 3, 'PG-13' );
INSERT INTO MPA_RATINGS VALUES ( 4, 'R' );
INSERT INTO MPA_RATINGS VALUES ( 5, 'NC-17' );

