INSERT INTO GENRES VALUES ( 1, 'Comedy' );
INSERT INTO GENRES VALUES ( 2, 'Drama' );
INSERT INTO GENRES VALUES ( 3, 'Cartoon' );
INSERT INTO GENRES VALUES ( 4, 'Thriller' );
INSERT INTO GENRES VALUES ( 5, 'Documentary' );
INSERT INTO GENRES VALUES ( 6, 'Action' );

INSERT INTO MPA_RATINGS VALUES ( 1, 'G' );
INSERT INTO MPA_RATINGS VALUES ( 2, 'PG' );
INSERT INTO MPA_RATINGS VALUES ( 3, 'PG-13' );
INSERT INTO MPA_RATINGS VALUES ( 4, 'R' );
INSERT INTO MPA_RATINGS VALUES ( 5, 'NC-17' );

INSERT INTO FRIENDSHIP_STATUSES VALUES ( 1, 'unconfirmed' );
INSERT INTO FRIENDSHIP_STATUSES VALUES ( 2, 'confirmed' );
